{{ prefixes }}

construct {

    ?auth a ?type;
        bf:authorizedAccessPoint ?key;
        dbpowl:influencedBy ?influence .

    ?influence bf:authorizedAccessPoint ?influence_key .

} where {

      service <http://dbpedia.org/sparql> {
        ?dbp_id dbpowl:influencedBy ?dbp_influence .
      }
      ?auth a ?type;
        owl:sameAs ?dbp_id;
        bf:authorizedAccessPoint ?key .
      ?influence
        owl:sameAs ?dbp_influence;
        bf:authorizedAccessPoint ?influence_key .

}

#construct {
#  ?s owl:sameAs ?same; libris:key ?name .
#} where {
#  ?s owl:sameAs ?same . ?s libris:key ?name .
#} LIMIT 100
